### ISSUE TITLE
The Checklist (was: Add README)

### ISSUE THREAD

**Issue by cobraz** [cobraz/parse-sitemap#15]
# Cheat sheet for releasing and maintaining GitHub actions

### :octocat: General
- [x] Are the `inputs` and `outputs` defined in `action.yml`, where applicable?
- [ ] Are tests present, potentially leveraging Actions?
- [x] Is the action published to GitHub Marketplace?

### 🗒 Documentation
- [ ] Is a `README` present with no typos?
- [ ] Are example workflow(s) in the `README`, ideally showing how the action can be used as part of a broader workflow?
- [ ] Are the prerequisites necessary in order for the example workflow to run included in `README`?
- [ ] Are `inputs` and `outputs` defined in `README`?
- [ ] Are [Workflow status badges](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge) and / or [third party badges](https://shields.io/) present in `README`?

### 🤝 Open source
- [ ] Are `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md` and other [community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types) present, like `FUNDING.md`, `SECURITY.md`, and `SUPPORT.md`?
- [ ] Are [issue and pull request templates](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) present? 

### 📦 Release management
- [x] Are [semantically tagged](https://docs.npmjs.com/about-semantic-versioning/) releases regularly made available, potentially leveraging Actions?
- [x] Are major / minor / patch tags kept up-to-date, potentially leveraging Actions?

### 🔁 Ongoing
- Keep the `README` up to date with changes
- Promptly respond to issues, discussions, and pull requests, potentially leveraging Actions
- Communicate future considerations or a feature roadmap, potentially leveraging GitHub project boards
